### ISSUE TITLE
ConfigSpace objects break SkOptimizer instantiation

### ISSUE THREAD

**Issue by nchristensen** [ytopt-team/ytopt#29]
The Optimizer class appears to have handling for ConfigurationSpace objects (https://github.com/ytopt-team/ytopt/blob/8c8f1f3e7cacb7312e9bda8b353ed713273ae984/ytopt/search/optimizer/optimizer.py#L43), but when I attempt to instantiate an AMBS object, it fails during the instantiation of the underlying SkOptimizer object. I'm using https://github.com/ytopt-team/scikit-optimize.

Reproducer:
```python
from autotune import TuningProblem
from autotune.space import *
from skopt.space import Real
from ytopt.search.ambs import AMBS
import ConfigSpace as cs

input_space = cs.ConfigurationSpace("autotuning_space")
input_space.add_hyperparameter(cs.Categorical("a", [0]))
output_space = Space([Real(0.0, inf, name="avg_time")])

def obj_func(p):
    return 1

problem = TuningProblem(
    task_space=None,
    input_space=input_space,
    output_space=output_space,
    objective=obj_func,
    constraints=None,
    model=None)

searcher = AMBS(problem=problem, evaluator="ray")
searcher.main()
```

Stack trace:
```
Uncaught exception <class 'ValueError'>: Dimension has to be a list or tuple.Traceback (most recent call last):
  File "/home/njchris2/Workspace/tagtune/ytopt_reproducer.py", line 22, in <module>
    searcher = AMBS(problem=problem, evaluator="subprocess")
  File "/home/njchris2/Workspace/ytopt/ytopt/search/ambs.py", line 48, in __init__
    self.optimizer = Optimizer(
  File "/home/njchris2/Workspace/ytopt/ytopt/search/optimizer/optimizer.py", line 44, in __init__
    self._optimizer = SkOptimizer(
  File "/home/njchris2/miniconda3/envs/dev/lib/python3.9/site-packages/skopt/optimizer/optimizer.py", line 271, in __init__
    self.space = Space(dimensions)
  File "/home/njchris2/miniconda3/envs/dev/lib/python3.9/site-packages/skopt/space/space.py", line 771, in __init__
    self.dimensions = [check_dimension(dim) for dim in dimensions]
  File "/home/njchris2/miniconda3/envs/dev/lib/python3.9/site-packages/skopt/space/space.py", line 771, in <listcomp>
    self.dimensions = [check_dimension(dim) for dim in dimensions]
  File "/home/njchris2/miniconda3/envs/dev/lib/python3.9/site-packages/skopt/space/space.py", line 91, in check_dimension
    raise ValueError("Dimension has to be a list or tuple.")
ValueError: Dimension has to be a list or tuple.
```

**Comment by nchristensen** [comment]
The issue seems to be [ytopt-team/scikit-optimize](https://github.com/ytopt-team/scikit-optimize) installs as `dh-scikit-optimize` and and installing it doesn't uninstall the `scikit-optimize` package. When skopt was import it imported it from `scikit-optimize` instead of `dh-scikit-optimize`. Since `scikit-optimize` doesn't have  handling for `ConfigSpace` objects, the `SkOptimizer` instantiation breaks. A simple fix is to uninstall `scikit-optimize`.
