### ISSUE TITLE
Breaking issue with YTOPT.

### ISSUE THREAD

**Issue by Sameeranjoshi** [ytopt-team/ytopt#55]
We have been running the tool for some internal work since last 5 months.
I have tried to recently rerun and some strange errors are seen recently.

```
~/workspace/SANDBOX/ytopt/ytopt/ytopt/ytopt/benchmark/mmm-block/mmm_problem$ python3 -m ytopt.search.ambs --evaluator ray --problem problem.Problem --max-evals=10 --learner RF

2023-07-26 15:21:33,509	INFO worker.py:1621 -- Started a local Ray instance.
Uncaught exception <class 'TypeError'>: Expected list, got setTraceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/sameeran/workspace/SANDBOX/ytopt/ytopt/ytopt/ytopt/search/ambs.py", line 125, in <module>
    search = AMBS(**vars(args))
  File "/home/sameeran/workspace/SANDBOX/ytopt/ytopt/ytopt/ytopt/search/ambs.py", line 48, in __init__
    self.optimizer = Optimizer(
  File "/home/sameeran/workspace/SANDBOX/ytopt/ytopt/ytopt/ytopt/search/optimizer/optimizer.py", line 44, in __init__
    self._optimizer = SkOptimizer(
  File "/home/sameeran/workspace/SANDBOX/ytopt/ytopt/scikit-optimize/skopt/optimizer/optimizer.py", line 315, in __init__
    self.space = Space(dimensions)
  File "/home/sameeran/workspace/SANDBOX/ytopt/ytopt/scikit-optimize/skopt/space/space.py", line 920, in __init__
    cond_hps = self.config_space.get_all_conditional_hyperparameters()
  File "ConfigSpace/configuration_space.pyx", line 1024, in **ConfigSpace.configuration_space.ConfigurationSpace.get_all_conditional_hyperparameters
TypeError: Expected list, got set**

```

Here's my git diff.

```
sameeran@echo11:~/workspace/SANDBOX/ytopt/ytopt/ytopt/ytopt/benchmark/mmm-block/mmm_problem$ git diff
diff --git a/ytopt/benchmark/mmm-block/mmm_problem/problem.py b/ytopt/benchmark/mmm-block/mmm_problem/problem.py
index aa7253a..ab9877f 100644
--- a/ytopt/benchmark/mmm-block/mmm_problem/problem.py
+++ b/ytopt/benchmark/mmm-block/mmm_problem/problem.py
@@ -13,8 +13,8 @@ from plopper import Plopper
 # create an object of ConfigSpace
 cs = CS.ConfigurationSpace(seed=1234)
 #block size for openmp dynamic schedule
-# p0= CSH.OrdinalHyperparameter(name='BLOCK_SIZE', sequence=['1','2','3','4','5','6','7','8','9','10'], default_value='5')
-p0= CSH.UniformIntegerHyperparameter(name='BLOCK_SIZE', lower=1, upper=10, default_value=5)
+p0= CSH.OrdinalHyperparameter(name='BLOCK_SIZE', sequence=['1','2','3','4','5','6','7','8','9','10'], default_value='5')
+#p0= CSH.UniformIntegerHyperparameter(name='BLOCK_SIZE', lower=1, upper=10, default_value=5)
 cs.add_hyperparameters([p0])
 
 # problem space
```

**Comment by wuxf99** [comment]
Sorry for the late response. One solution is to update the configspace under your conda env ytune: pip install configspace==0.7.1. This should solve the issues related to configspace.
